### ISSUE TITLE
暗骰指令 无法使用 gocq提示的目标好友为 0

### ISSUE THREAD

**Issue by kexue-z** [abrahum/nonebot_plugin_cocdicer#3]
# nb log

```
08-23 22:29:23 [ERROR] nonebot | Running matcher <Matcher from nonebot_plugin_cocdicer, type=message, priority=4, temp=False> failed.
Traceback (most recent call last):
  File "/nonebot/bot.py", line 30, in <module>
    nonebot.run(app="bot:app")
  File "/usr/local/lib/python3.9/site-packages/nonebot/__init__.py", line 277, in run
    get_driver().run(host, port, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 215, in run
    uvicorn.run(
  File "/usr/local/lib/python3.9/site-packages/uvicorn/main.py", line 393, in run
    server.run()
  File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 50, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.9/site-packages/nonebot/message.py", line 127, in _check_matcher
    await _run_matcher(Matcher, bot, event, state)
> File "/usr/local/lib/python3.9/site-packages/nonebot/message.py", line 155, in _run_matcher
    await matcher.run(bot, event, state)
  File "/usr/local/lib/python3.9/site-packages/nonebot/matcher.py", line 584, in run
    await handler(self, bot, event, self.state)
  File "/usr/local/lib/python3.9/site-packages/nonebot/handler.py", line 81, in __call__
    await self.func(
  File "/usr/local/lib/python3.9/site-packages/nonebot_plugin_cocdicer/__init__.py", line 73, in rdcommandhandler
    await bot.send_private_msg(user_id=uid, message=rrd[0])
  File "/usr/local/lib/python3.9/site-packages/nonebot/adapters/cqhttp/bot.py", line 416, in call_api
    return await super().call_api(api, **data)
  File "/usr/local/lib/python3.9/site-packages/nonebot/adapters/_base.py", line 181, in call_api
    raise exception
  File "/usr/local/lib/python3.9/site-packages/nonebot/adapters/_base.py", line 164, in call_api
    result = await self._call_api(api, **data)
  File "/usr/local/lib/python3.9/site-packages/nonebot/adapters/cqhttp/bot.py", line 363, in _call_api
    return _handle_api_result(await ResultStore.fetch(
  File "/usr/local/lib/python3.9/site-packages/nonebot/adapters/cqhttp/bot.py", line 192, in _handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.cqhttp.exception.ActionFailed: <ActionFailed data=None, echo={'seq': 10006}, msg=SEND_MSG_API_ERROR, retcode=100, status=failed, wording=请参考 go-cqhttp 端输出>
```

# gocq log 
```
[2021-08-23 22:29:23] [INFO]: 收到群 祝福(363342330) 内 孤独科宝。(278220060) 的消息: .rah (-2086007526) 
[2021-08-23 22:29:23] [ERROR]: 错误: 请先添加 (0) 为好友
```

# 其他

发送的指令 `.rah`
已添加好友
```
nonebot-plugin-cocdicer    0.2.4
nonebot2                               2.0.0a15
```

**Comment by abrahum** [comment]
0.2.5 已修复，错误的使用了`get_session_id` _(:з」∠)_

更新后应该就没问题了
